[targets.test]
name = "test"
method = "get"
url = "https://some_url/to/an/endpoints"

[targets.test.headers]
content_type = "application/json"

[targets.test.auth]
scheme = "bearer"
token = "token"

[targets.test.payload]
some_val = "val"
some_bool = true