name: Build Binary For macOS ARM64

on:
  workflow_dispatch:
    inputs:
      runs-on:
        type: choice
        default: macos-26
        options:
          - macos-14
          - macos-15
          - macos-26
          - macos-latest
        description: macOS version to run on

      rust-version:
        type: string
        default: stable
        description: Rust toolchain version used to build the binary

jobs:
  build:
    name: Build Binary For macOS ARM64
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout Code
        id: checkout-code
        uses: actions/checkout@v4

      - name: Install Rust
        id: install-rust
        run: rustup update ${{ inputs.rust-version }}

      - name: Build Debug Binary
        id: build-debug-binary
        run: cargo build

      - name: Build Release Binary
        id: build-binary
        run: cargo build --release

      - name: Set Artifact Prefix
        id: set-artifact-prefix
        run: |
          artifact_prefix=$(./target/release/snipe --version | tr '[:upper:] ' '[:lower:]_')
          echo Artifact prefix: $artifact_prefix
          echo "artifact_prefix=$artifact_prefix" >> $GITHUB_OUTPUT

      - name: Upload Debug Artifact
        id: upload-debug-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-artifact-prefix.outputs.artifact_prefix }}_debug
          path: target/debug/snipe

      - name: Upload Release Artifact
        id: upload-release-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-artifact-prefix.outputs.artifact_prefix }}_release
          path: target/release/snipe
