name: Build Binary For macOS ARM64

on:
  workflow_dispatch:
    inputs:
      runs-on:
        type: choice
        options:
          - macos-14
          - macos-15
        default: macos-15
        description: macOS version to run on

      rust-version:
        type: string
        default: stable
        description: Rust toolchain version used to build the binary

jobs:
  build:
    name: Build Binary For macOS ARM64
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout Code
        id: checkout-code
        uses: actions/checkout@v4

      - name: Install Rust
        id: install-rust
        run: rustup update ${{ inputs.rust-version }}

      - name: Build Binary
        id: build-binary
        run: cargo build --release

      - name: Upload Build Artifact
        id: upload-build-artifact
        uses: actions/upload-artifact@v4
        with:
          name: snipe
          path: target/release/snipe
