name: Build Binary For macOS ARM64

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Binary For macOS ARM64
    runs-on: macos-14
    steps:
      - name: Checkout Code
        id: checkout-code
        uses: actions/checkout@v4

      # Note - Pinning to 1.95.0 to match my local setup
      # If run 'rustup update' to update rust
      # want to run 'rustc --version' after updating
      # and update to dtolnay/resut-action@<version> below
      - name: Install Rust
        id: install-rust
        uses: dtolnay/rust-action@1.95.0

      - name: Build Binary
        id: build-binary
        run: cargo build --release

      - name: Upload Build Artifact
        id: upload-build-artifact
        uses: actions/upload-artifact@v4
        with:
          name: snipe
          path: target/release/snipe
